name: taskura_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.1.0+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  package_info_plus: ^8.3.0
  flutter_native_splash: ^2.4.6
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  file_picker: ^8.0.0+1
  url_launcher: ^6.3.1
  flutter_keyboard_visibility: ^6.0.0
  video_player: ^2.8.2
  chewie: ^1.7.5
  audioplayers: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_screen.png
    - assets/images/app_icon.png
    - assets/images/logo.png
    - assets/images/

flutter_native_splash:
  color: "#000000"
  image: assets/images/app_icon.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter_launcher_icons:
  image_path: assets/images/app_icon.png
  android: true
  ios: true
  adaptive_icon_background: "#000000"